### ISSUE TITLE
Textbox cannot be written to in Chromium browsers

### ISSUE THREAD

**Issue by dyaskur** [gomander/svelte-wheel#4]
Thanks for the nice project. 

Why can't I write to the name list textarea? I click to the name list and show the blink cursor, but can not write anything?

**Comment by gomander** [comment]
Can you open the browser devtools and see if you're getting any JS errors logged to the console? I haven't encountered that problem before. Also check if it works for you on https://sveltewheel.com. It could be an environment/Node version thing, perhaps?

**Comment by dyaskur** [comment]
I only tried https://svelte-wheel.firebaseapp.com/ and https://sveltewheel.com/ , never install on my local. and both of them can not write any text. I have tested Safari, Opera, and Arc browsers, but they all yield the same results. Perhaps that's only happening in mac?

On the devtools, I don't see any message.

**Comment by dyaskur** [comment]
I tried locally and it also the same, 

if I change [EntriesTextbox.svelte](https://github.com/gomander/svelte-wheel/blob/master/src/lib/components/EntriesTextbox.svelte#L9) code from`$: text = $wheelStore.entries.map(e => e.text).join('\n')` to `$: text = ''` , it's work. So I think the error is on $wheelStore

**Comment by dyaskur** [comment]
here the video recording to show how it doesnt work
https://github.com/gomander/svelte-wheel/assets/9539970/bc920b3c-bdfc-4bfe-ac76-c01cf56faefd

**Comment by gomander** [comment]
This looks like a Chromium-related bug. This works fine on Firefox, and while I was developing the app, it worked in Chromium browsers. It seems like there's been a change to how Chromium handles textarea content updates since I wrote the code initially.

Thanks for reporting this issue, I'll look into it!

**Comment by dyaskur** [comment]
You are welcome, hope it will be fixed soon.

I attempted to solve the issue on my own, but I'm not familiar with Svelte or reactive programming, so I couldn't fix it. I would like to use your project for my personal project and for learning purposes.
