### ISSUE TITLE
Where can i found this API Key?

### ISSUE THREAD

**Issue by harshascode** [gomander/svelte-wheel#5]
@gomander where can I find this? "SVELTE_WHEEL_API_KEY="

**Comment by gomander** [comment]
You can just put whatever you want there. It is the key for your own application.

**Comment by harshascode** [comment]
how can I implement different wheel in different routes? example: sveltewheel.com/animals which as animas name in it.

**Comment by gomander** [comment]
I'm sure it's possible, but I haven't made any effort to add a framework for that.

It's probably possible to remove the regex rule for matching wheel paths, then create and share the wheels you want and manually edit the document IDs and paths in Firestore from the default "abc-123" format to, for example, "animals". That way, it's fully data-driven and won't require a new deployment with new code to add new special wheels.
